image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy

default:
  before_script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda env create -f environment.yml
    - source activate eRNA

test:
  stage: test
  script:
    - snakemake --use-conda --directory .test || (for f in .test/logs/*; do echo $f; cat $f; done; for f in .test/logs/*/*; do echo $f; cat $f; done; exit 1)
    - snakemake --use-conda --directory .test --report report.html
  artifacts:
    paths:
      - .test/report.html

pages:
  stage: deploy
  script:
    - mkdir public
    - mv .test/report.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
