samples: samples.tsv

######################
# Rule configuration #
######################
feature_counts:
  annotation: 'data/2018-11-09/hg19/genes.gtf'
  extra: ''
  threads: 4

GM:
    A: data/samples/A.fastq
    B: data/samples/B.fastq
