samples: samples.tsv

######################
# Rule configuration #
######################
feature_counts:
  annotation: "data/2018-11-09/hg19/genes.gtf"
  extra: ""
  threads: 4

missing:
  - cell: IMR
    time: 9h
  - cell: IMR
    time: 18h
  - cell: IMR
    time: 48h
  - cell: IMR
    time: 72h
