samples: samples.tsv

histones:
  - H3K4me1
  - H3K27ac

missing:
  - cell: IMR
    unit: 9h
  - cell: IMR
    unit: 18h
  - cell: IMR
    unit: 48h
  - cell: IMR
    unit: 72h

ref:
  # the bowtie2 index
  index: "path/to/star/index"
  # gtf file with transcripts
  annotation: &annotation "data/2018-11-09/hg19/genes.gtf"

######################
# Rule configuration #
######################
feature_counts:
  annotation: *annotation
  extra: ""
  threads: 4
