samples: samples.tsv

missing:
  - cell: IMR
    unit: 9h
  - cell: IMR
    unit: 18h
  - cell: IMR
    unit: 48h
  - cell: IMR
    unit: 72h

######################
# Rule configuration #
######################
feature_counts:
  annotation: "data/2018-11-09/hg19/genes.gtf"
  extra: ""
  threads: 4
