        wget -qO- get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: python -m pip install --upgrade pip pytest-workflow

    # Test the module
    - run: nextflow run ./software/grohmm/test/ -profile docker
    - run: pytest --tag grohmm --symlink
