name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: snakemake/snakemake-github-action@v1.2
        with:
          directory: ".test"
          snakefile: workflow/Snakefile
          args: "--use-conda --use-singularity"
